[package]
name = "hexmake"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "hexmake"

[dependencies]
itertools = "0.14.0"
serde = {version ="1.0.219", features = ["derive", "rc"] }
serde_json = "1.0.140"

[dev-dependencies]
indoc = "2.0.6"
pretty_assertions = "1.4.1"
